const actionTypes = {
  UPLOAD_IMAGE: 'UPLOAD_IMAGE',
  POST_TWEET: 'POST_TWEET',
  TWEET_FEED: 'TWEET_FEED',
  USER_REGISTER: 'USER_REGISTER',
  USER_LOGIN: 'USER_LOGIN',
  TWEET_DETAILS: 'TWEET_DETAILS',
  GET_BOOKMARKS: 'GET_BOOKMARKS',
  GET_USER_PROFILE: 'GET_USER_PROFILE',
  GET_LIKED_TWEETS: 'GET_LIKED_TWEETS',
  SUCCESS: 'SUCCESS',
  ANALYTICS_PROFILE_VIEWS_PER_DAY: 'ANALYTICS_PROFILE_VIEWS_PER_DAY',
};

export default actionTypes;
